import Sidebar from '@/components/Sidebar';
import { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Taskify',
	description: 'Generated by create next app',
	icons: './taskify.svg',
};

export default function layout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<main className="flex min-h-screen max-h-screen  overflow-y-hidden">
			<Sidebar />
			{children}
		</main>
	);
}
