import Navbar from '@/components/Navbar';
import ConvexClientProvider from '@/context/ConvexClientProvider';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Taskify',
	description: 'Generated by create next app',
	icons: './taskify.svg',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ConvexClientProvider>
					<Navbar />
					<main className="flex flex-col bg-background min-h-[100vh] max-h-screen">
						{children}
					</main>
				</ConvexClientProvider>
			</body>
		</html>
	);
}
